sudo: false

language: python
python:
  - "3.5"

install:
  - pip install -U tox tox-travis pbr setuptools

script: make test

deploy:
  provider: pypi
  user: sirkonst
  password:
    secure: DvrPAUy0X32nBbJCsvDBnRvmtP77PyK8vT4MOtLfBw1Hdnxh+AyCClhY2n05e0F1YwQXhCFs8RIxlJ82GL4UIptQAuUWR8vpUjwoRmInQkvUYw06m50OMUK2TeP3xS8bd+vcXdUIpMdulaFca+Yrq8O1TtGEVok/g158rPWw4rlWA1q1J0q6YCMbslgUX1CAbfOqlW7FK/D5v9Hwc3BeZ26kGKEH0Ur7PEEMNFpM91g7lWyPkZSPg7UwgT3YOI5APLvA3VBtqQrilHXfhpua0SryYTGW57f5i1ia0nfkj0nGoRMVH3deRIxEKPbk/QIutSAudpVBjnkf53AF5isPYBOgnVwzaYmzUN6Meul69WY6pYs4hkhFFyQ1l5X06BUvFaDD9GmNkmqTySsNjf5TjTEBTrk+ugtjr28JvJcCBXl96I9dkovx1pYfIZahsdz1imqm+IP89byaYf9w0LLmvAQ/86uC34vpVioKCM3qT00fd4awYyMtK9a8+rMa97lpGe98UakAId1gk8M2Bz8rYbq0OjNjDtkOpeINudTSQ5at326mbU/LI73WfnXWemcUA5HNPS+v8mcPt2BXZFEVE5lQfWMw2LQOsVlC089x+OaNSHoIytcBxyLjQd1MKcxT+IeVztXHUfhs/IyFWd+IffybDgntMZ8qdzzS34ZedIU=
  on:
    tags: true
